steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/basicfast:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'basicfast-service', '--image', 'gcr.io/$PROJECT_ID/basicfast:$COMMIT_SHA', '--platform', 'managed', '--region', 'us-central1']
images:
- 'gcr.io/$PROJECT_ID/basicfast:$COMMIT_SHA'
